<Project Sdk="Microsoft.NET.Sdk">
<!-- Copyright (c)  Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information. -->
  <PropertyGroup>
    <Title>Acuminator Analyzers</Title>
    <AssemblyTitle>Acuminator.Tests</AssemblyTitle>
    <!-- Target framework must be net48 because net481 is not supported by our build system -->
    <TargetFramework>net48</TargetFramework>
    <Version>4.1.0</Version>
    <LangVersion>13.0</LangVersion>
    <Nullable>enable</Nullable>
    <WarningLevel>9999</WarningLevel>
    <NeutralLanguage>en</NeutralLanguage>
    <OutputPath>bin\$(Configuration)\</OutputPath>
    <RestorePackagesPath>../../packages</RestorePackagesPath>
</PropertyGroup>
  <PropertyGroup>
    <PackageLicenseUrl>https://github.com/Acumatica/Acuminator/blob/dev/LICENSE</PackageLicenseUrl>
    <PackageProjectUrl>https://github.com/Acumatica/Acuminator</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Acumatica/Acuminator</RepositoryUrl>
    <PackageReleaseNotes>https://github.com/Acumatica/Acuminator/blob/dev/docs/ReleaseNotes.md</PackageReleaseNotes>
  </PropertyGroup>
  <PropertyGroup>
    <Company>Acumatica, Inc.</Company>
    <Authors>$(Company)</Authors>	
    <Description>Unit tests for Acuminator</Description>
    <Copyright>Copyright © 2017-$([System.DateTime]::Now.Year) $(Company)</Copyright>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup>
    <NoWarn>$(NoWarn);PX1099;PX1120;VSTHRD200;CA1707;CA1708;CA1051</NoWarn>
  </PropertyGroup>
  <PropertyGroup>
    <DebugType>embedded</DebugType>
    <EnableNETAnalyzers>True</EnableNETAnalyzers>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
  </PropertyGroup>
  <PropertyGroup>
    <SignAssembly>false</SignAssembly>
    <WarningLevel>4</WarningLevel>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>
  <PropertyGroup>
    <RunPostBuildEvent>OnBuildSuccess</RunPostBuildEvent>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="ExternalDependency">
      <HintPath>ExternalDependency\Dll\ExternalDependency.dll</HintPath>
    </Reference>
    <Reference Include="PX.Common">
      <HintPath>..\..\..\lib\PX.Common.dll</HintPath>
    </Reference>
    <Reference Include="PX.Common.Std">
      <HintPath>..\..\..\lib\PX.Common.Std.dll</HintPath>
    </Reference>
    <Reference Include="PX.Data">
      <HintPath>..\..\..\lib\PX.Data.dll</HintPath>
    </Reference>
    <Reference Include="PX.Data.BQL.Fluent">
      <HintPath>..\..\..\lib\PX.Data.BQL.Fluent.dll</HintPath>
    </Reference>
    <Reference Include="PX.Objects">
      <HintPath>..\..\..\lib\PX.Objects.dll</HintPath>
    </Reference>
    <Reference Include="System.ComponentModel.Composition" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="Microsoft.VisualStudio.QualityTools.UnitTestFramework">
      <Private>false</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <!--Add exclusions because SDK projects include all .cs files for compilation by default and embedded resources record doesn't affect it -->
    <Compile Remove="Tests\StaticAnalysis\**\Sources\**\*.cs" />
    <Compile Remove="Tests\Utilities\**\Sources\**\*.cs" />
    <Compile Remove="Tests\Formatter\**\Sources\**\*.cs" />

    <!--Simplify all embedded resources via glob pattern 
      https://mykeels.medium.com/using-glob-patterns-in-csproj-files-95122c7f0870-->
    <EmbeddedResource Include="Tests\StaticAnalysis\**\Sources\**\*.cs" />
    <EmbeddedResource Include="Tests\Utilities\**\Sources\**\*.cs" />
    <EmbeddedResource Include="Tests\Formatter\**\Sources\**\*.cs" />
  </ItemGroup>
  <ItemGroup>
     <!--Add exclusions because SDK projects include all .cs files for compilation by default and None record doesn't affect it -->
    <Compile Remove="ExternalRunner\**\*.*" />
    <Compile Remove="ExternalDependency\**\*.*" />

    <None Include="ExternalRunner\**\*.*" />
    <None Include="ExternalDependency\**\*.*" />
    <None Include="FormatterTests.playlist" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="ExternalRunner\App\ExternalRunner.exe" />
    <Content Include="Tests\StaticAnalysis\BannedApi\BannedData\CustomBannedApis.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Tests\StaticAnalysis\BannedApi\BannedData\CustomAllowedApis.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ExternalDependency\Dll\ExternalDependency.dll" />
    <Content Include="Tests\DiagnosticSuppression\SuppressionFileIO\Examples\PX.Objects.acuminator" />
  </ItemGroup>
  <ItemGroup>
    <Service Include="{82A7F48D-3B50-4B1E-B82E-3ADA8210C358}" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Acuminator.Analyzers\Acuminator.Analyzers.csproj" />
    <ProjectReference Include="..\Acuminator.Utilities\Acuminator.Utilities.csproj" />
    <ProjectReference Include="..\Acuminator.Vsix\Acuminator.Vsix.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FluentAssertions" Version="5.4.2" />
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.4">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="3.11.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.VisualBasic.Workspaces" Version="3.11.0" />
    <PackageReference Include="Microsoft.Composition" Version="1.0.27" />
    <PackageReference Include="PolySharp" Version="1.15.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="System.Collections.Immutable" Version="8.0.0" />
    <PackageReference Include="System.Memory" Version="4.6.3" />
    <PackageReference Include="System.Reflection.Primitives" Version="4.3.0" />
    <PackageReference Include="System.Runtime.Handles" Version="4.1.0" />
    <PackageReference Include="xunit" Version="2.4.0" />
    <PackageReference Include="xunit.abstractions" Version="2.0.3" />
    <PackageReference Include="xunit.analyzers" Version="0.10.0" />
    <PackageReference Include="xunit.core" Version="2.4.0" />
    <PackageReference Include="xunit.runner.console" Version="2.4.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Tests\Refactorings\" />
  </ItemGroup>
  <Target Name="BuildExternalDependency" AfterTargets="PreBuildEvent">
    <MSBuild Projects="$(ProjectDir)ExternalDependency\src\ExternalDependency.csproj" Targets="Restore" />
    <MSBuild Projects="$(ProjectDir)ExternalDependency\src\ExternalDependency.csproj" Properties="Configuration=Debug" />
  </Target>
  <Target Name="BuildExternalExecutor" AfterTargets="PreBuildEvent">
    <MSBuild Projects="$(ProjectDir)ExternalRunner\src\ExternalRunner.csproj" Targets="Restore" />
    <MSBuild Projects="$(ProjectDir)ExternalRunner\src\ExternalRunner.csproj" Properties="Configuration=Debug" />
  </Target>
</Project>