//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acuminator.Analyzers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DiagnosticsShortName {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DiagnosticsShortName() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Acuminator.Analyzers.DiagnosticsShortName", typeof(DiagnosticsShortName).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidPXActionHandlerSignature.
        /// </summary>
        public static string PX1000 {
            get {
                return ResourceManager.GetString("PX1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PXGraphCreateInstance.
        /// </summary>
        public static string PX1001 {
            get {
                return ResourceManager.GetString("PX1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IncorrectTypeAttributeForListAttribute.
        /// </summary>
        public static string PX1002 {
            get {
                return ResourceManager.GetString("PX1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NonSpecificPXGraphCreateInstance.
        /// </summary>
        public static string PX1003 {
            get {
                return ResourceManager.GetString("PX1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewDeclarationOrderTwoCacheInstances.
        /// </summary>
        public static string PX1004 {
            get {
                return ResourceManager.GetString("PX1004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypoInViewDelegateName.
        /// </summary>
        public static string PX1005 {
            get {
                return ResourceManager.GetString("PX1005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewDeclarationOrderOneCacheInstance.
        /// </summary>
        public static string PX1006 {
            get {
                return ResourceManager.GetString("PX1006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoXmlCommentForPublicEntityOrDacProperty.
        /// </summary>
        public static string PX1007 {
            get {
                return ResourceManager.GetString("PX1007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LongOperationDelegateSynchronousExecution.
        /// </summary>
        public static string PX1008 {
            get {
                return ResourceManager.GetString("PX1008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InheritanceFromPXCacheExtension.
        /// </summary>
        public static string PX1009 {
            get {
                return ResourceManager.GetString("PX1009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartRowResetForPaging.
        /// </summary>
        public static string PX1010 {
            get {
                return ResourceManager.GetString("PX1010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InheritanceFromPXCacheExtension.
        /// </summary>
        public static string PX1011 {
            get {
                return ResourceManager.GetString("PX1011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PXActionOnNonPrimaryView.
        /// </summary>
        public static string PX1012 {
            get {
                return ResourceManager.GetString("PX1012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PXActionHandlerInvalidReturnType.
        /// </summary>
        public static string PX1013 {
            get {
                return ResourceManager.GetString("PX1013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NonNullableTypeForBqlField.
        /// </summary>
        public static string PX1014 {
            get {
                return ResourceManager.GetString("PX1014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IncorrectNumberOfSelectParameters.
        /// </summary>
        public static string PX1015 {
            get {
                return ResourceManager.GetString("PX1015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoPrimaryViewForPrimaryDac.
        /// </summary>
        public static string PX1018 {
            get {
                return ResourceManager.GetString("PX1018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NonStringPropertyTypeWithAutoNumberingAttribute.
        /// </summary>
        public static string PX1019 {
            get {
                return ResourceManager.GetString("PX1019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InsufficientStringLengthForAutoNumberingAttribute.
        /// </summary>
        public static string PX1020 {
            get {
                return ResourceManager.GetString("PX1020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FieldTypeAttributeAndPropertyTypeMismatch.
        /// </summary>
        public static string PX1021 {
            get {
                return ResourceManager.GetString("PX1021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NonPublicDacExtension.
        /// </summary>
        public static string PX1022Dac {
            get {
                return ResourceManager.GetString("PX1022Dac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NonPublicGraphExtension.
        /// </summary>
        public static string PX1022Graph {
            get {
                return ResourceManager.GetString("PX1022Graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MultipleTypeAttributesOnProperty.
        /// </summary>
        public static string PX1023 {
            get {
                return ResourceManager.GetString("PX1023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DacNonAbstractFieldType.
        /// </summary>
        public static string PX1024 {
            get {
                return ResourceManager.GetString("PX1024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnderscoresInDacDeclaration.
        /// </summary>
        public static string PX1026 {
            get {
                return ResourceManager.GetString("PX1026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForbiddenFieldsInDacDeclaration.
        /// </summary>
        public static string PX1027 {
            get {
                return ResourceManager.GetString("PX1027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConstructorInDacDeclaration.
        /// </summary>
        public static string PX1028 {
            get {
                return ResourceManager.GetString("PX1028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PXGraphUsageInDac.
        /// </summary>
        public static string PX1029 {
            get {
                return ResourceManager.GetString("PX1029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PXDefaultIncorrectUse.
        /// </summary>
        public static string PX1030 {
            get {
                return ResourceManager.GetString("PX1030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InstanceMethodInDac.
        /// </summary>
        public static string PX1031 {
            get {
                return ResourceManager.GetString("PX1031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MethodInvocationInDac.
        /// </summary>
        public static string PX1032 {
            get {
                return ResourceManager.GetString("PX1032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConstructorInGraphExtension.
        /// </summary>
        public static string PX1040 {
            get {
                return ResourceManager.GetString("PX1040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DatabaseQueriesInRowSelecting.
        /// </summary>
        public static string PX1042 {
            get {
                return ResourceManager.GetString("PX1042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SavingChangesInEventHandlers.
        /// </summary>
        public static string PX1043 {
            get {
                return ResourceManager.GetString("PX1043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChangesInPXCacheInEventHandlers.
        /// </summary>
        public static string PX1044 {
            get {
                return ResourceManager.GetString("PX1044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PXGraphCreateInstanceInEventHandlers.
        /// </summary>
        public static string PX1045 {
            get {
                return ResourceManager.GetString("PX1045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LongOperationInEventHandlers.
        /// </summary>
        public static string PX1046 {
            get {
                return ResourceManager.GetString("PX1046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RowChangesInEventHandlersForbiddenForArgs.
        /// </summary>
        public static string PX1047 {
            get {
                return ResourceManager.GetString("PX1047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RowChangesInEventHandlersAllowedForArgsOnly.
        /// </summary>
        public static string PX1048 {
            get {
                return ResourceManager.GetString("PX1048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DatabaseQueriesInRowSelected.
        /// </summary>
        public static string PX1049 {
            get {
                return ResourceManager.GetString("PX1049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HardcodedStringInLocalizationMethod.
        /// </summary>
        public static string PX1050 {
            get {
                return ResourceManager.GetString("PX1050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NonLocalizableString.
        /// </summary>
        public static string PX1051 {
            get {
                return ResourceManager.GetString("PX1051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IncorrectStringToFormat.
        /// </summary>
        public static string PX1052 {
            get {
                return ResourceManager.GetString("PX1052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConcatenationPriorLocalization.
        /// </summary>
        public static string PX1053 {
            get {
                return ResourceManager.GetString("PX1053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PXGraphLongRunOperationDuringInitialization.
        /// </summary>
        public static string PX1054 {
            get {
                return ResourceManager.GetString("PX1054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DacKeyFieldsWithIdentityKeyField.
        /// </summary>
        public static string PX1055 {
            get {
                return ResourceManager.GetString("PX1055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PXGraphCreationDuringInitialization.
        /// </summary>
        public static string PX1057 {
            get {
                return ResourceManager.GetString("PX1057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PXGraphSavingChangesDuringInitialization.
        /// </summary>
        public static string PX1058 {
            get {
                return ResourceManager.GetString("PX1058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChangesInPXCacheDuringPXGraphInitialization.
        /// </summary>
        public static string PX1059 {
            get {
                return ResourceManager.GetString("PX1059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LegacyBqlField.
        /// </summary>
        public static string PX1060 {
            get {
                return ResourceManager.GetString("PX1060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LegacyBqlConstant.
        /// </summary>
        public static string PX1061 {
            get {
                return ResourceManager.GetString("PX1061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UiPresentationLogicInEventHandlers.
        /// </summary>
        public static string PX1070 {
            get {
                return ResourceManager.GetString("PX1070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PXActionExecutionInEventHandlers.
        /// </summary>
        public static string PX1071 {
            get {
                return ResourceManager.GetString("PX1071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PXGraphCreationForBqlQueries.
        /// </summary>
        public static string PX1072 {
            get {
                return ResourceManager.GetString("PX1072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExceptionsInRowPersisted.
        /// </summary>
        public static string PX1073 {
            get {
                return ResourceManager.GetString("PX1073", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetupNotEnteredExceptionInEventHandlers.
        /// </summary>
        public static string PX1074 {
            get {
                return ResourceManager.GetString("PX1074", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RaiseExceptionHandlingInEventHandlers.
        /// </summary>
        public static string PX1075 {
            get {
                return ResourceManager.GetString("PX1075", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LongRunOperationInDataViewDelegate.
        /// </summary>
        public static string PX1080 {
            get {
                return ResourceManager.GetString("PX1080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionExecutionDuringPXGraphInitialization.
        /// </summary>
        public static string PX1081 {
            get {
                return ResourceManager.GetString("PX1081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionExecutionInDataViewDelegate.
        /// </summary>
        public static string PX1082 {
            get {
                return ResourceManager.GetString("PX1082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SavingChangesInDataViewDelegate.
        /// </summary>
        public static string PX1083 {
            get {
                return ResourceManager.GetString("PX1083", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GraphCreationInDataViewDelegate.
        /// </summary>
        public static string PX1084 {
            get {
                return ResourceManager.GetString("PX1084", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DatabaseQueriesInPXGraphInitialization.
        /// </summary>
        public static string PX1085 {
            get {
                return ResourceManager.GetString("PX1085", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetupNotEnteredExceptionInLongRunOperation.
        /// </summary>
        public static string PX1086 {
            get {
                return ResourceManager.GetString("PX1086", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StackOverflowExceptionInBaseViewDelegateInvocation.
        /// </summary>
        public static string PX1087 {
            get {
                return ResourceManager.GetString("PX1087", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidViewUsageInProcessingDelegate.
        /// </summary>
        public static string PX1088 {
            get {
                return ResourceManager.GetString("PX1088", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UiPresentationLogicInActionDelegates.
        /// </summary>
        public static string PX1089 {
            get {
                return ResourceManager.GetString("PX1089", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetupNotEnteredExceptionInActionHandlers.
        /// </summary>
        public static string PX1090 {
            get {
                return ResourceManager.GetString("PX1090", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StackOverflowExceptionInBaseActionHandlerInvocation.
        /// </summary>
        public static string PX1091 {
            get {
                return ResourceManager.GetString("PX1091", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IncorrectAttributesOnActionHandler.
        /// </summary>
        public static string PX1092 {
            get {
                return ResourceManager.GetString("PX1092", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GraphDeclarationViolation.
        /// </summary>
        public static string PX1093 {
            get {
                return ResourceManager.GetString("PX1093", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoPXHiddenOrPXCacheNameOnDac.
        /// </summary>
        public static string PX1094 {
            get {
                return ResourceManager.GetString("PX1094", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoUnboundTypeAttributeWithPXDBCalced.
        /// </summary>
        public static string PX1095 {
            get {
                return ResourceManager.GetString("PX1095", resourceCulture);
            }
        }
    }
}
