//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acuminator.Analyzers {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Acuminator.Analyzers.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fix PXAction handler signature.
        /// </summary>
        public static string PX1000Fix {
            get {
                return ResourceManager.GetString("PX1000Fix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid PXAction handler signature.
        /// </summary>
        public static string PX1000Title {
            get {
                return ResourceManager.GetString("PX1000Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create a graph instance by using the factory method.
        /// </summary>
        public static string PX1001Fix {
            get {
                return ResourceManager.GetString("PX1001Fix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A PXGraph instance must be created with the PXGraph.CreateInstance() factory method.
        /// </summary>
        public static string PX1001Title {
            get {
                return ResourceManager.GetString("PX1001Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add the type attribute corresponding to the list attribute.
        /// </summary>
        public static string PX1002Fix {
            get {
                return ResourceManager.GetString("PX1002Fix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The field must have the type attribute corresponding to the list attribute.
        /// </summary>
        public static string PX1002Title {
            get {
                return ResourceManager.GetString("PX1002Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Consider using a specific implementation of PXGraph.
        /// </summary>
        public static string PX1003Title {
            get {
                return ResourceManager.GetString("PX1003Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Consider changing the declaration order.
        /// </summary>
        public static string PX1004Fix {
            get {
                return ResourceManager.GetString("PX1004Fix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This order of view declarations will cause creation of two cache instances: {0} and {1}.
        /// </summary>
        public static string PX1004Title {
            get {
                return ResourceManager.GetString("PX1004Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change the view delegate name to match the view name.
        /// </summary>
        public static string PX1005Fix {
            get {
                return ResourceManager.GetString("PX1005Fix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A possible typo in the view delegate name. The view name for this delegate: {0}.
        /// </summary>
        public static string PX1005MessageFormat {
            get {
                return ResourceManager.GetString("PX1005MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A possible typo in the view delegate name.
        /// </summary>
        public static string PX1005Title {
            get {
                return ResourceManager.GetString("PX1005Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Consider changing the declaration order.
        /// </summary>
        public static string PX1006Fix {
            get {
                return ResourceManager.GetString("PX1006Fix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This order of view declarations will cause creation of one cache instance for the following DACs: {0} and {1}.
        /// </summary>
        public static string PX1006Title {
            get {
                return ResourceManager.GetString("PX1006Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create a DAC instance by using the factory method.
        /// </summary>
        public static string PX1007Fix {
            get {
                return ResourceManager.GetString("PX1007Fix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An instance of {0} must be created with the PXCache&lt;{0}&gt;.CreateInstance() factory method.
        /// </summary>
        public static string PX1007MessageFormat {
            get {
                return ResourceManager.GetString("PX1007MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A DAC instance must be created with the PXCache.CreateInstance() factory method.
        /// </summary>
        public static string PX1007Title {
            get {
                return ResourceManager.GetString("PX1007Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reference of @this graph in this delegate will cause synchronous delegate execution.
        /// </summary>
        public static string PX1008Title {
            get {
                return ResourceManager.GetString("PX1008Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change the base type to a PXCacheExtension overload.
        /// </summary>
        public static string PX1009Fix {
            get {
                return ResourceManager.GetString("PX1009Fix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Multiple levels of inheritance are not supported for PXCacheExtension.
        /// </summary>
        public static string PX1009Title {
            get {
                return ResourceManager.GetString("PX1009Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset StartRow.
        /// </summary>
        public static string PX1010Fix {
            get {
                return ResourceManager.GetString("PX1010Fix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на If a delegate applies paging in an inner select, StartRow must be reset (If StartRow is not reset, paging will be applied twice).
        /// </summary>
        public static string PX1010Title {
            get {
                return ResourceManager.GetString("PX1010Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mark the type as sealed.
        /// </summary>
        public static string PX1011Fix {
            get {
                return ResourceManager.GetString("PX1011Fix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Because multiple levels of inheritance are not supported for PXCacheExtension, the derived type can be marked as sealed.
        /// </summary>
        public static string PX1011Title {
            get {
                return ResourceManager.GetString("PX1011Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change the type parameter of the action to the primary DAC ({0}).
        /// </summary>
        public static string PX1012Fix {
            get {
                return ResourceManager.GetString("PX1012Fix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The type parameter of the {0} action is not the primary DAC. You should specify the {1} DAC as the type parameter to make the action available on the toolbar..
        /// </summary>
        public static string PX1012Title {
            get {
                return ResourceManager.GetString("PX1012Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Make the type nullable.
        /// </summary>
        public static string PX1014Fix {
            get {
                return ResourceManager.GetString("PX1014Fix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A DAC field must have a nullable type.
        /// </summary>
        public static string PX1014Title {
            get {
                return ResourceManager.GetString("PX1014Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The number of arguments passed to the {0} method does not match the number of BQL statement parameters. The number of required arguments is {1}..
        /// </summary>
        public static string PX1015TitleSuffixWithOnlyRequiredParams {
            get {
                return ResourceManager.GetString("PX1015TitleSuffixWithOnlyRequiredParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The number of arguments passed to the {0} method does not match the number of BQL statement parameters. The number of arguments should be from {1} to {2}..
        /// </summary>
        public static string PX1015TitleSuffixWithRequiredAndOptionalParams {
            get {
                return ResourceManager.GetString("PX1015TitleSuffixWithRequiredAndOptionalParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The graph with the specified primary DAC type does not contain a view of this type.
        /// </summary>
        public static string PX1018Title {
            get {
                return ResourceManager.GetString("PX1018Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change the property type so that it corresponds to the attribute type.
        /// </summary>
        public static string PX1021PropertyFix {
            get {
                return ResourceManager.GetString("PX1021PropertyFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The type of the DAC field attribute does not correspond to the property type.
        /// </summary>
        public static string PX1021Title {
            get {
                return ResourceManager.GetString("PX1021Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Leave the selected field attribute and remove other field attributes from the property.
        /// </summary>
        public static string PX1023Fix {
            get {
                return ResourceManager.GetString("PX1023Fix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The DAC property cannot be marked with multiple field attributes.
        /// </summary>
        public static string PX1023Title {
            get {
                return ResourceManager.GetString("PX1023Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Make the DAC field type abstract.
        /// </summary>
        public static string PX1024Fix {
            get {
                return ResourceManager.GetString("PX1024Fix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The DAC field type must be abstract.
        /// </summary>
        public static string PX1024Title {
            get {
                return ResourceManager.GetString("PX1024Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove underscores from the DAC declaration.
        /// </summary>
        public static string PX1026Fix {
            get {
                return ResourceManager.GetString("PX1026Fix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Underscores cannot be used in DAC declarations.
        /// </summary>
        public static string PX1026Title {
            get {
                return ResourceManager.GetString("PX1026Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Replace with the PXUnboundDefaultAttribute or set PersistingCheck to Nothing.
        /// </summary>
        public static string PX1030Fix {
            get {
                return ResourceManager.GetString("PX1030Fix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Incorrect PXDefaultAttribute to exisiting field .
        /// </summary>
        public static string PX1030Title {
            get {
                return ResourceManager.GetString("PX1030Title", resourceCulture);
            }
        }
    }
}
