//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acuminator.Utilities {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Acuminator.Utilities.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The diagnostic cannot be added to the suppression file. Check if file {0} is accessible..
        /// </summary>
        public static string DiagnosticSuppression_FailedToAddToSuppressionFile {
            get {
                return ResourceManager.GetString("DiagnosticSuppression_FailedToAddToSuppressionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The suppression file for the assembly {0} cannot be found..
        /// </summary>
        public static string DiagnosticSuppression_FailedToFindSuppressionFile {
            get {
                return ResourceManager.GetString("DiagnosticSuppression_FailedToFindSuppressionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t set buld action. The suppression file for the assembly {0} cannot be found..
        /// </summary>
        public static string DiagnosticSuppression_FailedToFindSuppressionFileToSetBuildAction {
            get {
                return ResourceManager.GetString("DiagnosticSuppression_FailedToFindSuppressionFileToSetBuildAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set build action for the suppression file {0}..
        /// </summary>
        public static string DiagnosticSuppression_FailedToSetBuildAction {
            get {
                return ResourceManager.GetString("DiagnosticSuppression_FailedToSetBuildAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acuminator cannot load the suppression file. The suppression mechanism will be turned off. If you fix the error, the suppression mechanism will be turned on automatically..
        /// </summary>
        public static string FailedToLoadTheSuppressionFile {
            get {
                return ResourceManager.GetString("FailedToLoadTheSuppressionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error details:{0}..
        /// </summary>
        public static string FailedToLoadTheSuppressionFileDetails {
            get {
                return ResourceManager.GetString("FailedToLoadTheSuppressionFileDetails", resourceCulture);
            }
        }
    }
}
