//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PX.Analyzers {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PX.Analyzers.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix PXAction handler signature.
        /// </summary>
        internal static string PX1000Fix {
            get {
                return ResourceManager.GetString("PX1000Fix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PXAction handler signature.
        /// </summary>
        internal static string PX1000Title {
            get {
                return ResourceManager.GetString("PX1000Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create graph using factory method.
        /// </summary>
        internal static string PX1001Fix {
            get {
                return ResourceManager.GetString("PX1001Fix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PXGraph instance should be created using PXGraph.CreateInstance() factory method.
        /// </summary>
        internal static string PX1001Title {
            get {
                return ResourceManager.GetString("PX1001Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List attribute should have correspoding type attribute.
        /// </summary>
        internal static string PX1002Fix {
            get {
                return ResourceManager.GetString("PX1002Fix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List attribute should have correspoding type attribute.
        /// </summary>
        internal static string PX1002Title {
            get {
                return ResourceManager.GetString("PX1002Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consider using specific implementation of PXGraph.
        /// </summary>
        internal static string PX1003Title {
            get {
                return ResourceManager.GetString("PX1003Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consider changing declaration order.
        /// </summary>
        internal static string PX1004Fix {
            get {
                return ResourceManager.GetString("PX1004Fix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This order of views declaration will result in creation of 2 distinct caches {0} {1}.
        /// </summary>
        internal static string PX1004Title {
            get {
                return ResourceManager.GetString("PX1004Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename view delegate name to match view name.
        /// </summary>
        internal static string PX1005Fix {
            get {
                return ResourceManager.GetString("PX1005Fix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible typo in view delegate name. View name for this delegate: &apos;{0}&apos;.
        /// </summary>
        internal static string PX1005MessageFormat {
            get {
                return ResourceManager.GetString("PX1005MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible typo in view delegate name.
        /// </summary>
        internal static string PX1005Title {
            get {
                return ResourceManager.GetString("PX1005Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consider changing declaration order.
        /// </summary>
        internal static string PX1006Fix {
            get {
                return ResourceManager.GetString("PX1006Fix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This order of views declaration will result in creation of 1 cache for both dacs {0} {1}.
        /// </summary>
        internal static string PX1006Title {
            get {
                return ResourceManager.GetString("PX1006Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create DAC instance using factory method.
        /// </summary>
        internal static string PX1007Fix {
            get {
                return ResourceManager.GetString("PX1007Fix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; instance should be created using PXCache&lt;{0}&gt;.CreateInstance() factory method.
        /// </summary>
        internal static string PX1007MessageFormat {
            get {
                return ResourceManager.GetString("PX1007MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAC instance should be created using PXCache.CreateInstance() factory method.
        /// </summary>
        internal static string PX1007Title {
            get {
                return ResourceManager.GetString("PX1007Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This delegate references @this graph which will result in synchronous delegate execution.
        /// </summary>
        internal static string PX1008Title {
            get {
                return ResourceManager.GetString("PX1008Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change base type to PXCacheExtension overload.
        /// </summary>
        internal static string PX1009Fix {
            get {
                return ResourceManager.GetString("PX1009Fix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple levels of inheritance are not supported for PXCacheExtension.
        /// </summary>
        internal static string PX1009Title {
            get {
                return ResourceManager.GetString("PX1009Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset StartRow.
        /// </summary>
        internal static string PX1010Fix {
            get {
                return ResourceManager.GetString("PX1010Fix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartRow must be reset if delegate returns applies paging in inner select (or paging will be applied twice).
        /// </summary>
        internal static string PX1010Title {
            get {
                return ResourceManager.GetString("PX1010Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark type as sealed.
        /// </summary>
        internal static string PX1011Fix {
            get {
                return ResourceManager.GetString("PX1011Fix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple levels of inheritance are not supported for PXCacheExtension, so derived type can be marked as sealed..
        /// </summary>
        internal static string PX1011Title {
            get {
                return ResourceManager.GetString("PX1011Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The BQL statement doesn&apos;t meet the Code Style requirements .
        /// </summary>
        internal static string PXF1001Title {
            get {
                return ResourceManager.GetString("PXF1001Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format the BQL statement to meet the Code Style requirements .
        /// </summary>
        internal static string PXF1002Fix {
            get {
                return ResourceManager.GetString("PXF1002Fix", resourceCulture);
            }
        }
    }
}
