//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PX.Analyzers {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PX.Analyzers.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix PXAction handler signature.
        /// </summary>
        internal static string PX1000Fix {
            get {
                return ResourceManager.GetString("PX1000Fix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PXAction handler signature.
        /// </summary>
        internal static string PX1000Title {
            get {
                return ResourceManager.GetString("PX1000Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create graph using factory method.
        /// </summary>
        internal static string PX1001Fix {
            get {
                return ResourceManager.GetString("PX1001Fix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PXGraph instance should be created using PXGraph.CreateInstance() factory method.
        /// </summary>
        internal static string PX1001Title {
            get {
                return ResourceManager.GetString("PX1001Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List attribute {0} should have correspoding type attribute.
        /// </summary>
        internal static string PX1002Fix {
            get {
                return ResourceManager.GetString("PX1002Fix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks ups list attributes without corresponding type attribute.
        /// </summary>
        internal static string PX1002Title {
            get {
                return ResourceManager.GetString("PX1002Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consider using specific implementation of PXGraph.
        /// </summary>
        internal static string PX1003Title {
            get {
                return ResourceManager.GetString("PX1003Title", resourceCulture);
            }
        }
    }
}
