using System.Threading.Tasks;

using Acuminator.Analyzers.StaticAnalysis;
using Acuminator.Analyzers.StaticAnalysis.PXGraphCreateInstance;
using Acuminator.Tests.Verification;
using Acuminator.Utilities;
using Acuminator.Utilities.DiagnosticSuppression;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;

using Xunit;

namespace Acuminator.Tests.Tests.DiagnosticSuppression
{
	/// <summary>
	/// Tests for the fallback diagnostic suppression with *.acuminator suppression files passed to the compilation as additional files.
	/// This mechanism is used when Acuminator is installed as a NuGet package and there is no host (VSIX package or console runner)
	/// to initialize the <see cref="SuppressionManager"/> instance.
	/// </summary>
	public class AdditionalFileSuppressionTests : DiagnosticVerifier
	{
		/// <summary>
		/// The suppression file name must match the assembly name that <see cref="SolutionBuilder"/> uses for test compilations
		/// (<c>GenProject</c>), because the suppression file is matched to the project by the assembly name.
		/// </summary>
		private const string SuppressionFileName = "GenProject.acuminator";

		/// <summary>
		/// Hardcoded suppression file content for the PX1001 diagnostic reported on <c>new MyGraph()</c> in <see cref="Source"/>.
		/// It is intentionally hardcoded (not generated by <c>SuppressMessage.GetSuppressionInfo</c>) so that a change to the format
		/// of the stored target or syntax node - which would break existing users' suppression files - makes these tests fail.
		/// </summary>
		private const string SuppressionFileContent = @"<?xml version=""1.0"" encoding=""utf-8""?>
<suppressions>
  <suppressMessage id=""PX1001"">
    <target>Acuminator.Tests.Sources.GraphCreator.Prefetch()</target>
    <syntaxNode>new MyGraph()</syntaxNode>
  </suppressMessage>
</suppressions>";

		private const string Source = @"
using PX.Data;

namespace Acuminator.Tests.Sources
{
	public class GraphCreator : IPrefetchable
	{
		public void Prefetch()
		{
			var graph = new MyGraph();
		}
	}

	public class MyGraph : PXGraph<MyGraph>
	{
	}
}";

		protected override DiagnosticAnalyzer GetCSharpDiagnosticAnalyzer() =>
			new PXGraphCreateInstanceAnalyzer(CodeAnalysisSettings.Default
																  .WithStaticAnalysisEnabled()
																  .WithSuppressionMechanismEnabled());

		[Fact]
		public Task WithoutSuppressionFile_DiagnosticIsReported() =>
			VerifyCSharpDiagnosticAsync(Source, Descriptors.PX1001_PXGraphCreateInstance.CreateFor(line: 10, column: 16));

		[Fact]
		public Task SuppressedInAdditionalFile_DiagnosticIsNotReported() =>
			VerifyCSharpDiagnosticAsync(Source, new[] { new InMemoryAdditionalText(SuppressionFileName, SuppressionFileContent) });

		[Fact]
		public Task SuppressionFileForAnotherAssembly_DiagnosticIsReported() =>
			VerifyCSharpDiagnosticAsync(Source, new[] { new InMemoryAdditionalText("SomeOtherAssembly.acuminator", SuppressionFileContent) },
										Descriptors.PX1001_PXGraphCreateInstance.CreateFor(line: 10, column: 16));

		[Fact]
		public async Task SuppressionMechanismDisabled_DiagnosticIsReported()
		{
			var suppressionFile = new InMemoryAdditionalText(SuppressionFileName, SuppressionFileContent);
			var analyzerWithDisabledSuppression =
				new PXGraphCreateInstanceAnalyzer(CodeAnalysisSettings.Default
																	  .WithStaticAnalysisEnabled()
																	  .WithSuppressionMechanismDisabled());

			var diagnostics = await GetSortedDiagnosticsAsync(new[] { Source }, LanguageNames.CSharp,
															  analyzerWithDisabledSuppression, checkOnlyFirstDocument: true,
															  additionalFiles: new[] { suppressionFile });

			Assert.Single(diagnostics);
			Assert.Equal(Descriptors.PX1001_PXGraphCreateInstance.Id, diagnostics[0].Id);
		}
	}
}
