//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PX.Analyzers.Vsix {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VSIXResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VSIXResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PX.Analyzers.Vsix.Resources.VSIXResource", typeof(VSIXResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acuminator - BQL constant - ending.
        /// </summary>
        public static string BQLConstantEndingFormatLabel {
            get {
                return ResourceManager.GetString("BQLConstantEndingFormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acuminator - BQL constant - prefix.
        /// </summary>
        public static string BQLConstantPrefixFormatLabel {
            get {
                return ResourceManager.GetString("BQLConstantPrefixFormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acuminator - BQL operators.
        /// </summary>
        public static string BQLOperatorFormatLabel {
            get {
                return ResourceManager.GetString("BQLOperatorFormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acuminator - BQL parameters.
        /// </summary>
        public static string BQLParameterFormatLabel {
            get {
                return ResourceManager.GetString("BQLParameterFormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acuminator - BQL angle braces level 1.
        /// </summary>
        public static string BraceLevel_1_FormatLabel {
            get {
                return ResourceManager.GetString("BraceLevel_1_FormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acuminator - BQL angle braces level 10.
        /// </summary>
        public static string BraceLevel_10_FormatLabel {
            get {
                return ResourceManager.GetString("BraceLevel_10_FormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acuminator - BQL angle braces level 11.
        /// </summary>
        public static string BraceLevel_11_FormatLabel {
            get {
                return ResourceManager.GetString("BraceLevel_11_FormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acuminator - BQL angle braces level 12.
        /// </summary>
        public static string BraceLevel_12_FormatLabel {
            get {
                return ResourceManager.GetString("BraceLevel_12_FormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acuminator - BQL angle braces level 13.
        /// </summary>
        public static string BraceLevel_13_FormatLabel {
            get {
                return ResourceManager.GetString("BraceLevel_13_FormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acuminator - BQL angle braces level 14.
        /// </summary>
        public static string BraceLevel_14_FormatLabel {
            get {
                return ResourceManager.GetString("BraceLevel_14_FormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acuminator - BQL angle braces level 2.
        /// </summary>
        public static string BraceLevel_2_FormatLabel {
            get {
                return ResourceManager.GetString("BraceLevel_2_FormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acuminator - BQL angle braces level 3.
        /// </summary>
        public static string BraceLevel_3_FormatLabel {
            get {
                return ResourceManager.GetString("BraceLevel_3_FormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acuminator - BQL angle braces level 4.
        /// </summary>
        public static string BraceLevel_4_FormatLabel {
            get {
                return ResourceManager.GetString("BraceLevel_4_FormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acuminator - BQL angle braces level 5.
        /// </summary>
        public static string BraceLevel_5_FormatLabel {
            get {
                return ResourceManager.GetString("BraceLevel_5_FormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acuminator - BQL angle braces level 6.
        /// </summary>
        public static string BraceLevel_6_FormatLabel {
            get {
                return ResourceManager.GetString("BraceLevel_6_FormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acuminator - BQL angle braces level 7.
        /// </summary>
        public static string BraceLevel_7_FormatLabel {
            get {
                return ResourceManager.GetString("BraceLevel_7_FormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acuminator - BQL angle braces level 8.
        /// </summary>
        public static string BraceLevel_8_FormatLabel {
            get {
                return ResourceManager.GetString("BraceLevel_8_FormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acuminator - BQL angle braces level 9.
        /// </summary>
        public static string BraceLevel_9_FormatLabel {
            get {
                return ResourceManager.GetString("BraceLevel_9_FormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acuminator.
        /// </summary>
        public static string Category_Acuminator {
            get {
                return ResourceManager.GetString("Category_Acuminator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acuminator - DAC Extension Name.
        /// </summary>
        public static string DacExtensionFormatLabel {
            get {
                return ResourceManager.GetString("DacExtensionFormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acuminator - DAC Field Name.
        /// </summary>
        public static string DacFieldFormatLabel {
            get {
                return ResourceManager.GetString("DacFieldFormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acuminator - DAC Name.
        /// </summary>
        public static string DacFormatLabel {
            get {
                return ResourceManager.GetString("DacFormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acuminator - PXAction.
        /// </summary>
        public static string PXActionFormatLabel {
            get {
                return ResourceManager.GetString("PXActionFormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acuminator - PXGraph.
        /// </summary>
        public static string PXGraphFormatLabel {
            get {
                return ResourceManager.GetString("PXGraphFormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax coloring enabled.
        /// </summary>
        public static string Setting_ColoringEnabled_Description {
            get {
                return ResourceManager.GetString("Setting_ColoringEnabled_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coloring enabled.
        /// </summary>
        public static string Setting_ColoringEnabled_Title {
            get {
                return ResourceManager.GetString("Setting_ColoringEnabled_Title", resourceCulture);
            }
        }
    }
}
